# .gitlab-ci.yml

stages:
  - build
  - deploy

variables:
  REGISTRY: "registry.gitlab.com/officialbektur/downloading-content-by-scrolling"

before_script:
  - echo "huina"

app_build:
  stage: build
  tags:
    - build
  only:
    - develop
  script:
    - echo "cxcxc"
