stages:
  - build
  - develop

variables:
  REGISTRY: "registry.gitlab.com/laravelcreative/laravelcicd"

before_script:
  - echo $CI_REGISTRY
  - echo $CI_REGISTRY_USER
  - echo $CI_REGISTRY_PASSWORD
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

app_build:
  stage: build
  tags:
    - build
  only:
    - develop
  script:
    - docker build --build-arg NODE_ENV="dev" -t "$REGISTRY/dev/app:$CI_COMMIT_SHA" -f ./_docker/cicd/app/Dockerfile .
    - docker push "$REGISTRY/dev/app:$CI_COMMIT_SHA"
