stages:
  - first
  - third
  - second

print_first:
  stage: first
  tags:
    - build
  only:
    - develop
  script:
    - echo "Hello word first"

print_second:
    stage: second
    tags:
      - build
    only:
      - develop
    script:
      - echo "Hello word second"

print_third:
    stage: third
    tags:
      - build
    only:
      - develop
    script:
      - echo "Hello word third"
