# .gitlab-ci.yml

stages:
  - build  # Определение стадии сборки
  - deploy  # Определение стадии развертывания

variables:
  REGISTRY: "registry.gitlab.com/officialbektur/downloading-content-by-scrolling"  # Переменная для указания Docker Registry

before_script:
  - echo "huina"

app_build:
  stage: build  # Задача сборки относится к стадии сборки
  tags:
    - build  # Используем тег "build" для выполнения на соответствующих агентах
  only:
    - develop  # Выполнять задачу только для ветки develop
  script:
    - echo "cxcxc"
